### ISSUE TITLE
Fails to parse some GNU attributes

### ISSUE THREAD

**Issue by cdisselkoen** [BinaryAnalysisPlatform/FrontC#8]
FrontC fails to parse `__attribute__((__aligned__(__alignof__(long long))))`.  This appears in `stddef.h` on my system, or technically in `__stddef_max_align_t.h` which is #included in `stddef.h`.

I believe the root cause of the problem is that [here](https://github.com/BinaryAnalysisPlatform/FrontC/blob/be30bc971d3555ac27f1e427aac25cc350d43c2a/frontc/cparser.mly#L1143), the rule which matches `__alignof__(*)` expects an identifier, a constant, or another expression involving parens, but instead it gets `long long`.

**Comment by ivg** [comment]
The `long long` built-in type was introduced only in C99 and FrontC supports only C89. So it is the expected behavior, see also #9. 

If you want to introduce the C99 built-in types, i.e., `long long`, `_Bool`, `_Complex`, and `_Imaginary`, you need to add them to the built-in lexicon of identifiers [here][1], e.g., 
```ocaml
		("long long", id LLONG);
```

and add the corresponding tokens (`LLONG`, `BOOL`, `COMPLEX`, and `IMAGINARY`), [here][3]. We probably also need to update the [scan_ident][2] primitive so that it accepts strings like `long .. <many spaces> ..long`<sup>1</sup>, i.e., we need to strip repetitive whitespace. 

Finally, we will need to deal with [the ambiguity][4] in the modifier parser that our change will introduce. As previously `long long` was not parsed as a builtin type, but rather than a modifier to `long` so that `long long x;` was accepted but `sizeof(long long)` or `alignof(long long)` were not. 

[1]: https://github.com/BinaryAnalysisPlatform/FrontC/blob/be30bc971d3555ac27f1e427aac25cc350d43c2a/frontc/clexer.mll#L138
[2]: https://github.com/BinaryAnalysisPlatform/FrontC/blob/be30bc971d3555ac27f1e427aac25cc350d43c2a/frontc/clexer.mll#L209
[3]: https://github.com/BinaryAnalysisPlatform/FrontC/blob/master/frontc/cparser.mly#L180
[4]: https://github.com/BinaryAnalysisPlatform/FrontC/blob/master/frontc/cparser.mly#L65

--------

<sup>1)</sup> Githubs markdown eats consecutive spaces even inside backticked strings, but you got the idea.

**Comment by ivg** [comment]
In fact, the main culprit is that gnu attributes are not allowed in a structure field definition.
