### ISSUE TITLE
Fails to parse re-typedefs

### ISSUE THREAD

**Issue by cdisselkoen** [BinaryAnalysisPlatform/FrontC#9]
FrontC fails to parse the following:
```
typedef int a;
typedef int b;
typedef b a;
```
even though this is accepted by `clang`.

Probably related is that FrontC fails to parse the following:
```
typedef int a;
typedef int a;
```
even though this is also accepted by `clang`.

**Comment by cdisselkoen** [comment]
My guess is that FrontC sees the first typedef as `typedef <type> <ident>`, but the second as `typedef <type> <type>` which doesn't parse.  Perhaps the solution is to add a case for `<type>` to [`typedef_dec`](https://github.com/BinaryAnalysisPlatform/FrontC/blob/be30bc971d3555ac27f1e427aac25cc350d43c2a/frontc/cparser.mly#L570)

**Comment by ivg** [comment]
Sorry for the delayed reply, I was on a vacation. FrontC supports C89 and some pieces of C99. The declaration of typedefs was only allowed in C11 (section 6.7/3), therefore it is an expected and well-formed behavior. 

The project was abandoned by its original authors so we adopted it to give it some retirement plan as there are still a few packages that depend on it. I would suggest switching to some other C frontend, instead of relying on FrontC in new projects as we don't have any intentions to update this project and add new features.

We would, in general, accept pull requests with the new features but the project doesn't have any testing infrastructure and it is hard to assess the impact of the change in the grammar on its correctness, especially with respect to the type definitions. FrontC uses an ugly approach of maintaining a hashtable of names so that the grammar itself is hiddenly changed when a new typedef is introduced. Therefore allowing redefinitions of type might introduce a nasty interplay between the state of the parser and the hidden state that holds typedefs. Or might not.
